In [1]:
from numpy import array
from numpy import random
from numpy import dot
from scipy.special import softmax

In [2]:
# embeddings de palabras
word_1 = array([1, 0, 0]) # Tengo
word_2 = array([0, 1, 0]) # hambre
word_3 = array([1, 1, 0]) # quiero
word_4 = array([0, 0, 1]) # una
word_5 = array([1, 1, 1]) # hamburguesa

In [3]:
# matrices de pesos (Esto debería venir de la red neuronal)
W_Q = random.randint(3, size=(3, 3))
W_K = random.randint(3, size=(3, 3))
W_V = random.randint(3, size=(3, 3))

In [ ]:
# Generamos los vectores de q, k y v para cada palabra. Si los unimos formamos las matrices Q, K y V
query_1 = word_1 @ W_Q
key_1 = word_1 @ W_K
value_1 = word_1 @ W_V

query_2 = word_2 @ W_Q
key_2 = word_2 @ W_K
value_2 = word_2 @ W_V

query_3 = word_3 @ W_Q
key_3 = word_3 @ W_K
value_3 = word_3 @ W_V

query_4 = word_4 @ W_Q
key_4 = word_4 @ W_K
value_4 = word_4 @ W_V

query_5 = word_5 @ W_Q
key_5 = word_5 @ W_K
value_5 = word_5 @ W_V

In [ ]:
query_1

array([0, 2, 2])

In [ ]:
# calculamos los puntajes de la palabra perro contra todas las demás
scores = array([dot(query_1, key_1), dot(query_1, key_2), dot(query_1, key_3), dot(query_1, key_4), dot(query_1, key_5)])

In [ ]:
scores

array([ 6,  6, 12,  2, 14])

In [ ]:
# normalizamos los vectores de puntaje (para convertirlos en atención)
weights = softmax(scores / key_1.shape[0] ** 0.5)

In [ ]:
weights

array([7.38445560e-03, 7.38445560e-03, 2.35916708e-01, 7.33429441e-04,
       7.48580951e-01])

In [ ]:
value_1

array([2, 2, 1])

In [ ]:
# obtenemos el vector contextualizado
attention = (weights[0] * value_1) + (weights[1] * value_2) + (weights[2] * value_3) + (weights[3] * value_4)

print(attention)

[0.48660233 0.97320465 0.24403459]


In [ ]:
# en forma matricial
words = array([word_1, word_2, word_3, word_4, word_5])

Q = words @ W_Q
K = words @ W_K
V = words @ W_V

scores = Q @ K.transpose()

weights = softmax(scores / K.shape[1] ** 0.5, axis=1)

attention = weights @ V

In [ ]:
attention

array([[1.98376423, 3.96752846, 1.7411965 ],
       [1.98272771, 3.95398901, 1.73652501],
       [1.9998199 , 3.99950151, 1.90933883],
       [1.96505928, 3.68919112, 1.41110709],
       [1.99999443, 3.99989502, 1.90960214]])

In [ ]:
words

array([[1, 0, 0],
       [0, 1, 0],
       [1, 1, 0],
       [0, 0, 1],
       [1, 1, 1]])