In [ ]:
!pip install -q transformers
!pip install -q datasets

In [ ]:
sentence = "I read an interesting book"

In [ ]:
from transformers import BertTokenizer, BertModel
import torch.nn as nn
import torch

In [ ]:
class BertEncoder(nn.Module):
    def __init__(self, bert_model_name):
        super(BertEncoder, self).__init__()
        self.bert = BertModel.from_pretrained(bert_model_name)

    def forward(self, input_ids, attention_mask):
        with torch.no_grad():
            outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
            pooled_output = outputs.pooler_output # Linear Layer and Tanh activation function
            sequence_output = outputs.last_hidden_state
        return pooled_output, sequence_output

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
tokenizer.tokenize(sentence)

['i', 'read', 'an', 'interesting', 'book']

In [ ]:
tokenized_sentence = tokenizer(text=sentence, add_special_tokens=True, return_attention_mask=True, return_tensors='pt')

In [ ]:
tokenized_sentence

{'input_ids': tensor([[ 101, 1045, 3191, 2019, 5875, 2338,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
tokenizer.convert_ids_to_tokens(tokenizer(text=sentence, add_special_tokens=True, return_attention_mask=True)["input_ids"])

['[CLS]', 'i', 'read', 'an', 'interesting', 'book', '[SEP]']

In [ ]:
input_ids = tokenized_sentence["input_ids"]
attention_mask = tokenized_sentence["attention_mask"]

In [ ]:
input_ids

tensor([[ 101, 1045, 3191, 2019, 5875, 2338,  102]])

In [ ]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1]])

In [ ]:
model = BertEncoder("bert-base-uncased")

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
model.bert.config

BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [ ]:
output = model.forward(input_ids, attention_mask)

In [ ]:
len(output)

2

In [ ]:
output[0].shape

torch.Size([1, 768])

In [ ]:
output[0]

tensor([[-6.9454e-01, -1.1729e-01,  7.4710e-01,  2.9774e-01, -3.8085e-01,
         -1.8350e-02,  6.9451e-01,  1.6230e-01,  4.8279e-01, -9.9769e-01,
          2.8250e-01, -5.1387e-02,  9.6195e-01, -5.1735e-01,  8.4172e-01,
         -2.2652e-01,  2.1032e-01, -4.1382e-01,  2.4640e-01, -2.7574e-01,
          3.5597e-01,  2.5157e-01,  6.6049e-01,  1.8611e-01,  1.8761e-01,
         -1.8671e-01, -3.1185e-01,  8.6501e-01,  8.8723e-01,  5.4346e-01,
         -3.9717e-01,  1.0478e-01, -9.6906e-01, -6.3697e-02,  7.4102e-01,
         -9.5831e-01,  1.0043e-02, -5.9722e-01,  7.7998e-02,  1.5658e-01,
         -8.0847e-01,  1.7895e-01,  9.5660e-01, -4.0519e-01, -1.2422e-01,
         -2.1704e-01, -9.7061e-01,  1.1867e-01, -7.2374e-01, -7.0554e-01,
         -5.2738e-01, -6.7143e-01, -3.5462e-03,  1.8794e-01,  1.8016e-01,
          5.7383e-01, -2.4321e-01,  1.8786e-02, -1.4217e-02, -2.8539e-01,
         -5.1701e-01,  1.4996e-01,  4.2380e-01, -7.7169e-01, -5.5731e-01,
         -7.8177e-01, -7.3886e-03, -9.

In [ ]:
output[1].shape

torch.Size([1, 7, 768])

In [ ]:
input_ids.shape

torch.Size([1, 7])